title:              SonicCho
email:              gustkd0@gmail.com
description:        DevBlog by SonicCho
author:             SonicCho
baseurl:            ""
url:                "https://github.com/soniccho/soniccho.github.io.git"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
